namespace CP.Dto.Caas
{
    public class DirectDebitRequestDto
    {
        /// <summary>
        /// Used to identify the application. This is a unique identifier generated while provisioning 
        /// an application.Only a single value can be sent per request. (String (32) - Mandatory)
        /// </summary>
        public string applicationId { get; set; }

        /// <summary>
        /// Used to authenticate the application originated message against the service providers credentials.
        /// Encoded, single value. (String (32) - Mandatory)
        /// </summary>
        public string password { get; set; }

        /// <summary>
        /// This is the transaction ID generated by the application to map the request with the response.
        /// This is needed to avoid any conflicts when SP inquires about a transaction.
        /// Only a single value can be sent per request. (String (32) - Mandatory)
        /// </summary>
        public string externalTrxId { get; set; }

        /// <summary>
        /// TThis can be the MSISDN the subscriber to be charged. This is a unique identifier.
        /// Tel: is for MSISDN tel:947758456325
        /// Note: tel might be a masked number depending on the type of the application.
        /// Only a single value can be sent per request.. (Mandatory)
        /// </summary>
        public string subscriberId { get; set; }

        /// <summary>
        /// The name of the payment instrument.Only a single value can be sent per request. (Enum - Mandatory)
        /// </summary>
        public string paymentInstrumentName { get; set; }

        /// <summary>
        /// The account of the payment instrument.Only a single value can be sent per request. (Optional)
        /// </summary>
        public string accountId { get; set; }

        /// <summary>
        /// Amount to be reserved for charging.Only a single value can be sent per request. String(rounded up to two decimal points)(Mandatory)
        /// </summary>
        public string amount { get; set; }

        /// <summary>
        /// The currency of the amount.Only a single value can be sent per request.Only ‘LKR’ is allowed. (Optional)
        /// </summary>
        public string currency { get; set; }

        /// <summary>
        /// A Json object with key value pairs for additional parameters.
        /// Eg:{“ezcashAgentPin”:”4444?,”ezcashAgentAlias”:”VC_0000?   }
        /// This is used to manage additional parameters specific for eZ cash payment instruments.
        /// </summary>
        public string additionalParams { get; set; }


        /* Comprehensive sample request:    
         {  
             “applicationId”: “APP_000017”,

            “password”: “95904999aa8edb0c038b3295fdd271de”,

            “externalTrxId”: “12345678901234567890123456789012”,

            “subscriberId”: “94771234567”,

            “paymentInstrumentName”: “MobileAccount”,

            “accountId”: “123456”,

            “currency”: “LKR”,

            “amount”: “100”
        } */

    }
}
