//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleChatApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoupleChatApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while saving and linking user {0} on DB..
        /// </summary>
        internal static string Error_AddAndLinkUserFailed {
            get {
                return ResourceManager.GetString("Error_AddAndLinkUserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot couple user with the given code. Please try again..
        /// </summary>
        internal static string Error_CannotCoupleUser {
            get {
                return ResourceManager.GetString("Error_CannotCoupleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured when charge from user {0}..
        /// </summary>
        internal static string Error_ChargeFailed {
            get {
                return ResourceManager.GetString("Error_ChargeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your friend is already coupled with another User.  To send message to a non coupled friend type &quot;CC #&lt;Friend&apos;s Code&gt; &lt;Your Message&gt;&quot;  and  send SMS to 77117..
        /// </summary>
        internal static string Error_CodeAlreadyLinked {
            get {
                return ResourceManager.GetString("Error_CodeAlreadyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get user code failed..
        /// </summary>
        internal static string Error_GetUserCodeFailed {
            get {
                return ResourceManager.GetString("Error_GetUserCodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Please type &quot;CC &lt;Your Message&gt;&quot; and send SMS  to 77117 again..
        /// </summary>
        internal static string Error_InvalidChatFormat {
            get {
                return ResourceManager.GetString("Error_InvalidChatFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in friend&apos;s code. Please enter valid friend&apos;s code and try again..
        /// </summary>
        internal static string Error_InvalidCode {
            get {
                return ResourceManager.GetString("Error_InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input message. Please check your message format. To get help type &quot;CC #HELP&quot; and  send SMS to 77117..
        /// </summary>
        internal static string Error_InvalidInputMessage {
            get {
                return ResourceManager.GetString("Error_InvalidInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sms format. Please check your message format. To get help type &quot;CC #HELP&quot; and  send SMS to 77117..
        /// </summary>
        internal static string Error_InvalidSmsFormat {
            get {
                return ResourceManager.GetString("Error_InvalidSmsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Message cannot be sent. You are not coupled with another friend. Type &quot;CC #ADD &lt;Friend&apos;s Code&gt;&quot; and send SMS to 77117 to link with a friend..
        /// </summary>
        internal static string Error_NotLinkedUser {
            get {
                return ResourceManager.GetString("Error_NotLinkedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove linked user failed..
        /// </summary>
        internal static string Error_RemoveLinkedUserFailed {
            get {
                return ResourceManager.GetString("Error_RemoveLinkedUserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry. You only can have one coupled friend at a time. To send message to a non coupled friend type &quot;CC #&lt;Friend&apos;s Code&gt; &lt;Your Message&gt;&quot; or to get help type &quot;CC #HELP&quot; and  send SMS to 77117..
        /// </summary>
        internal static string Error_UserAlreadyLinked {
            get {
                return ResourceManager.GetString("Error_UserAlreadyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while saving user {0} on DB..
        /// </summary>
        internal static string Error_UserSaveFailed {
            get {
                return ResourceManager.GetString("Error_UserSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your code is {0}. Share your code with your friend to start chat. Type &quot;CC #HELP&quot; to get instructions..
        /// </summary>
        internal static string Info_GetUserCode {
            get {
                return ResourceManager.GetString("Info_GetUserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) To couple your friend type &quot;CC #ADD &lt;Friend&apos;s Code&gt;&quot; 
        ///2) To send message to a coupled friend type &quot;CC &lt;Your Message&gt;&quot;
        ///3) To send message to a non coupled friend type &quot;CC #&lt;Friend&apos;s Code&gt; &lt;Your Message&gt;&quot;
        ///4) To remove your coupled friend type &quot;CC #DEL&quot;
        ///5) To get your unique code type &quot;CC #CODE&quot;
        ///6) To get help type &quot;CC #HELP&quot;
        ///And send SMS to 77117..
        /// </summary>
        internal static string Info_Help {
            get {
                return ResourceManager.GetString("Info_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for registering Couple Chat service. Your user code is {0}. Now ask your friend to register and request his/her code to share with you. To couple your friend type &quot;CC #ADD &lt;Friend&apos;s Code&gt;&quot;. Type &quot;CC #HELP&quot; to get help..
        /// </summary>
        internal static string Info_RegisterSuccess {
            get {
                return ResourceManager.GetString("Info_RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your friend and you are linked now. You can start chat. Type &quot;CC &lt;Your Message&gt;&quot; and send SMS to 77117..
        /// </summary>
        internal static string Info_RegisterSuccessCoupleUser {
            get {
                return ResourceManager.GetString("Info_RegisterSuccessCoupleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your coupled user has been removed successfully. To couple with a new friend type &quot;CC #ADD &lt;Friend&apos;s Code&gt;&quot; or to get help type &quot;CC #HELP&quot; and  send SMS to 77117..
        /// </summary>
        internal static string Info_RemoveLinkedUser {
            get {
                return ResourceManager.GetString("Info_RemoveLinkedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been unsubscribed from the Couple Chat service. Thank you for using Couple Chat..
        /// </summary>
        internal static string Info_UnregisterSuccess {
            get {
                return ResourceManager.GetString("Info_UnregisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already registered. Your code is {0}. Share your code with your friend to use our service..
        /// </summary>
        internal static string Info_UserAlreadyRegistered {
            get {
                return ResourceManager.GetString("Info_UserAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users:{0} Couples:{1}.
        /// </summary>
        internal static string Info_UserCount {
            get {
                return ResourceManager.GetString("Info_UserCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not registered to the service..
        /// </summary>
        internal static string Info_UserNotRegistered {
            get {
                return ResourceManager.GetString("Info_UserNotRegistered", resourceCulture);
            }
        }
    }
}
